<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="receptes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recepta" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nom"/>
              <xs:element name="autor" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nom"/>
                    <xs:element name="dni">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[0-9]{8}[A-Z]{1}"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="ingredients" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingredient" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="quantitat">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:integer" name="valor"/>
                                <xs:element type="xs:string" name="mesura"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="nom"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="passos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="pas" maxOccurs="unbounded" minOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="dificultat">
              <xs:simpleType>
                <xs:restriction base="xs:integer">
                  <xs:maxInclusive value="10"/>
                  <xs:minInclusive value="0"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="categoria">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="primer"/>
                  <xs:enumeration value="segon"/>
                  <xs:enumeration value="postre"/>
                  <xs:enumeration value="altres"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>